version: '3'
services:
  mongodb:
    container_name: mongodatabase
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null

volumes:
  # mongodbdata:
  #   driver: local
  appdata:
    driver: local